CREATE TABLE IF NOT EXISTS TB_ATIVIDADES( 
            ID int NOT NULL AUTO_INCREMENT PRIMARY KEY, 
            TITULO varchar(255) NOT NULL,
            TIPO varchar(255) NOT NULL,
            DATA_REAL DATE NOT NULL, 
            QTDE_HORAS int NOT NULL,
            SITUACAO varchar(255) NOT NULL
);

INSERT INTO TB_ATIVIDADES (TITULO, TIPO, DATA_REAL, QTDE_HORAS, SITUACAO) 
            VALUES ('2019 uma odisseia no Java', 'CULTURAL','2019-08-20', 10,'ENTREGUE');
INSERT INTO TB_ATIVIDADES (TITULO, TIPO, DATA_REAL, QTDE_HORAS, SITUACAO) 
            VALUES ('Piratas do Vale', 'CULTURAL','2019-07-25', 10,'ENTREGUE');
INSERT INTO TB_ATIVIDADES (TITULO, TIPO, DATA_REAL, QTDE_HORAS, SITUACAO) 
            VALUES ('Aula LPOO', 'MONITORIA','2019-08-01', 50,'APROVADA');
INSERT INTO TB_ATIVIDADES (TITULO, TIPO, DATA_REAL, QTDE_HORAS, SITUACAO) 
            VALUES ('Piratas do Vale', 'CULTURAL','2019-07-25', 10,'ENTREGUE');

