CREATE TABLE IF NOT EXISTS TB_CURSOS( 
            ID int NOT NULL AUTO_INCREMENT PRIMARY KEY, 
            NOME varchar(255) NOT NULL,
            TIPO varchar(255) NOT NULL,
            CARGA_HORARIA int NOT NULL, 
            COD_INSTITUTO  varchar(255) NOT NULL
);

INSERT INTO TB_CURSOS (NOME, TIPO, CARGA_HORARIA, COD_INSTITUTO) 
            VALUES ('CIENCIAS_BIOLOGICAS', 'BACHAREL',300,'AX2ASD');
INSERT INTO TB_CURSOS (NOME, TIPO, CARGA_HORARIA, COD_INSTITUTO) 
            VALUES ('CIENCIAS_DA_COMPUTACAO', 'BACHAREL',200,'T312SX');
